/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.miumg.gt.clinicamedicas.vistas;


import edu.miumg.gt.clinicamedicas.entities.Paciente;
import edu.miumg.gt.clinicamedicas.ws.inte.PacienteInt;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author BYRON TOLEDO
 */
public class Persona extends javax.swing.JFrame {

    /**
     * Creates new form Persona
     */
    
    
    @Autowired()
    PacienteInt pacienteInt;
    
        
    @Autowired()
    Menu menu;
    
     DefaultComboBoxModel ComboxPaciente;
    
    public Persona() {
        initComponents();
        
        JcomboxEstado.setModel(GenerarEstadoCivil());
        
    }
    
    
    private void PersonaRegistrar(){
            if("".equals(Jnombretxt.getText())){
            JOptionPane.showMessageDialog(this, "El Campo Nombre Vacio", "Persona", JOptionPane.DEFAULT_OPTION);
            return;
            }
            if("".equals(Japellidotxt.getText())){
            JOptionPane.showMessageDialog(this, "El Campo Apellido Vacio", "Persona", JOptionPane.DEFAULT_OPTION);
            return;
            }
            if("".equals(Jdirecciontxt.getText())){
            JOptionPane.showMessageDialog(this, "El Campo Direccion Vacio", "Persona", JOptionPane.DEFAULT_OPTION);
            return;
            }
            if("".equals(Jedadtxt.getText())){
            JOptionPane.showMessageDialog(this, "El Campo Edad Vacio", "Persona", JOptionPane.DEFAULT_OPTION);
            return;
            }
            if(JfechaNacimiento.getDate()==null){
            JOptionPane.showMessageDialog(this, "El Campo Fecha Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
            }
            
            Paciente paciente = new Paciente();
            Paciente persona1 = new Paciente();
            
            paciente.setNombre(Jnombretxt.getText().trim());
            paciente.setApellido(Japellidotxt.getText().trim());
            paciente.setDireccion(Jdirecciontxt.getText().trim());
            paciente.setEdad(Integer.valueOf(Jedadtxt.getText().trim()));
            paciente.setEstadoCivil(JcomboxEstado.getItemAt(JcomboxEstado.getSelectedIndex()).trim());
            paciente.setFechaNacimiento(JfechaNacimiento.getDate());
            
            if(jRadioM.isSelected()==true){
            paciente.setSexo(1);
            }else{
            paciente.setSexo(0);
            }
            
            try{
            persona1 = pacienteInt.save(paciente);
            }catch(Exception ex){
              JOptionPane.showMessageDialog(null,"Ha ocurrido un error inesperado: "+ex.getMessage());
            }finally{
            
                JOptionPane.showMessageDialog(null,"Datos Ingresados Correctamente: "+persona1.getNombre()+" "+persona1.getApellido());
            
                Jnombretxt.setText("");
                Japellidotxt.setText("");
                Jdirecciontxt.setText("");
                Jedadtxt.setText("");
                JfechaNacimiento.setCalendar(null);
                jRadioM.setSelected(true);
                JcomboxEstado.removeAllItems();
                ComboxPaciente.removeAllElements();
                GenerarEstadoCivil().removeAllElements();
                JcomboxEstado.setModel(GenerarEstadoCivil());  
                menu.setLocationRelativeTo(null);
                menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
                menu.setVisible(true);
                this.setVisible(false);
            }
    }
    
    
    private DefaultComboBoxModel GenerarEstadoCivil(){
    
        ComboxPaciente = new  DefaultComboBoxModel();
        
        ComboxPaciente.addElement("--seleccione--");
        ComboxPaciente.addElement("CASADO");
        ComboxPaciente.addElement("SOLTERO");
        ComboxPaciente.addElement("UNIDOS");
        ComboxPaciente.addElement("OTROS");
        
        
        return ComboxPaciente;
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jnombretxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Japellidotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jdirecciontxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        JcomboxEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Jedadtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JfechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jRadioM = new javax.swing.JRadioButton();
        jRadioF = new javax.swing.JRadioButton();
        JguardarPaciente = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Jregresar = new javax.swing.JButton();
        JcancelarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Nombres:");

        Jnombretxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Apellidos:");

        Japellidotxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Direccion:");

        Jdirecciontxt.setColumns(20);
        Jdirecciontxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jdirecciontxt.setLineWrap(true);
        Jdirecciontxt.setRows(5);
        Jdirecciontxt.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Jdirecciontxt);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Estado Civil:");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Edad:");

        Jedadtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Jedadtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Fecha Nacimiento:");

        JfechaNacimiento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Sexo:");

        buttonGroup1.add(jRadioM);
        jRadioM.setSelected(true);
        jRadioM.setText("M");

        buttonGroup1.add(jRadioF);
        jRadioF.setText("F");

        JguardarPaciente.setIcon(new javax.swing.ImageIcon("C:\\Users\\BYRON TOLEDO\\Documents\\NetBeansProjects\\ClinicaMedicas\\src\\main\\java\\IMAGENES\\diskette.png")); // NOI18N
        JguardarPaciente.setText("GUARDAR");
        JguardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JguardarPacienteActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRAR PACIENTE");

        Jregresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\BYRON TOLEDO\\Documents\\NetBeansProjects\\ClinicaMedicas\\src\\main\\java\\IMAGENES\\return-button.png")); // NOI18N
        Jregresar.setText("REGRESAR");
        Jregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JregresarActionPerformed(evt);
            }
        });

        JcancelarDatos.setIcon(new javax.swing.ImageIcon("C:\\Users\\BYRON TOLEDO\\Documents\\NetBeansProjects\\ClinicaMedicas\\src\\main\\java\\IMAGENES\\x-button.png")); // NOI18N
        JcancelarDatos.setText("CANCELAR");
        JcancelarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcancelarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(JguardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioF))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Jnombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Japellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JcomboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(Jedadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(JfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Jregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JcancelarDatos))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jregresar)
                    .addComponent(JcancelarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Japellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JfechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(JcomboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jedadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioM)
                    .addComponent(jRadioF))
                .addGap(18, 18, 18)
                .addComponent(JguardarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JguardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JguardarPacienteActionPerformed
        PersonaRegistrar();
    }//GEN-LAST:event_JguardarPacienteActionPerformed

    private void JcancelarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcancelarDatosActionPerformed
                
        try{
                Jnombretxt.setText("");
                Japellidotxt.setText("");
                Jdirecciontxt.setText("");
                Jedadtxt.setText("");
                JfechaNacimiento.setCalendar(null);
                jRadioM.setSelected(true);
                JcomboxEstado.removeAllItems();
                ComboxPaciente.removeAllElements();
                GenerarEstadoCivil().removeAllElements();
                JcomboxEstado.setModel(GenerarEstadoCivil());
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Ha ocurrido un error inesperado: "+ex.getMessage());
        }
        
                 
    }//GEN-LAST:event_JcancelarDatosActionPerformed

    private void JregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JregresarActionPerformed
        menu.setLocationRelativeTo(null);
        menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JregresarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Persona().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Japellidotxt;
    private javax.swing.JButton JcancelarDatos;
    private javax.swing.JComboBox<String> JcomboxEstado;
    private javax.swing.JTextArea Jdirecciontxt;
    private javax.swing.JTextField Jedadtxt;
    private com.toedter.calendar.JDateChooser JfechaNacimiento;
    private javax.swing.JButton JguardarPaciente;
    private javax.swing.JTextField Jnombretxt;
    private javax.swing.JButton Jregresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioF;
    private javax.swing.JRadioButton jRadioM;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
