/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.miumg.gt.clinicamedicas.vistas;

import edu.miumg.gt.clinicamedicas.entities.Especialista;
import edu.miumg.gt.clinicamedicas.entities.Usuario;
import edu.miumg.gt.clinicamedicas.util.EncryptMd5;
import edu.miumg.gt.clinicamedicas.ws.inte.EspecialistaInt;
import edu.miumg.gt.clinicamedicas.ws.inte.UsuarioInt;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;



/**
 *
 * @author BYRON TOLEDO
 */
public class Registrar extends javax.swing.JFrame {

   

    /**
     * Creates new form Registrar
     */
    List<Especialista> especialidad;
    DefaultComboBoxModel Combox1;
        
    @Autowired()
    EspecialistaInt especialistaInt;
    
    @Autowired()
    UsuarioInt usuarioInt;

    @Autowired()
    Login login;

    public Registrar(){
        initComponents();
                                    
    }
    
    private void RegistrarDatos(){
        
        if("".equals(Jnombretxt.getText())){
         JOptionPane.showMessageDialog(this, "El Campo Nombre Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        if("".equals(Japellidotxt.getText())){
        JOptionPane.showMessageDialog(this, "El Campo Apellido Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        if("".equals(Jedadtxt.getText())){
        JOptionPane.showMessageDialog(this, "El Campo Edad Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
             
        if("".equals(Jusuariotxt.getText())){
        JOptionPane.showMessageDialog(this, "El Campo Usuario Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        if("".equals(Jpasswordtxt.getText())){
        JOptionPane.showMessageDialog(this, "El Campo Password Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        if(JDatenacimiento.getDate()==null){
        JOptionPane.showMessageDialog(this, "El Campo Fecha Vacio", "Registrar", JOptionPane.DEFAULT_OPTION);
            return;
        }
        
        Usuario usuario = new Usuario();
        usuario.setNombre(Jnombretxt.getText().trim());
        usuario.setApellido(Japellidotxt.getText().trim());
        usuario.setEdad(Integer.valueOf(Jedadtxt.getText().trim()));
        
        if(JRadioM.isSelected()==true){
        usuario.setSexo(1);
        }else{
        usuario.setSexo(0);
        }
        
        usuario.setFechaNacimineto(JDatenacimiento.getDate());
        usuario.setUsuario(Jusuariotxt.getText().trim());
        
        String password = new String(Jpasswordtxt.getPassword());
        
        usuario.setPassword(EncryptMd5.get_md5(password));
        
        try{
        usuarioInt.save(usuario,especialidad.get(JComboxespecialista.getSelectedIndex()).getId());
        }catch(Exception ex){
        System.err.println(ex.getMessage());
        } finally{
        JOptionPane.showMessageDialog(null,"Ingresado Exitosamente");
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.setVisible(false);
        }              
    }
    
    private DefaultComboBoxModel generarEspecialista(){
        
        Combox1 = new DefaultComboBoxModel();
        
        try {
            especialidad = especialistaInt.findAllEspecialista();

            for (int i = 0; i < especialidad.size(); i++) {

                Combox1.addElement(especialidad.get(i).getTipoEspecialidad());

            }
        } catch (Exception ex) {
            
            System.err.println(ex);

        }
        
        return Combox1;

    }
        
               
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jnombretxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Japellidotxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jedadtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JRadioM = new javax.swing.JRadioButton();
        JRadioF = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        JDatenacimiento = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        Jusuariotxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jpasswordtxt = new javax.swing.JPasswordField();
        JComboxespecialista = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        JButtonguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRES:");

        Jnombretxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("APELLIDOS:");

        Japellidotxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRAR USUARIO");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("EDAD:");

        Jedadtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("SEXO:");

        sexo.add(JRadioM);
        JRadioM.setSelected(true);
        JRadioM.setText("M");
        JRadioM.setLabel("M");

        sexo.add(JRadioF);
        JRadioF.setText("F");
        JRadioF.setLabel("F");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("FECHA NACIMIENTO:");

        JDatenacimiento.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("USUARIO:");

        Jusuariotxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("PASSWORD:");

        Jpasswordtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        JComboxespecialista.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JComboxespecialista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargardatosCombox(evt);
            }
        });
        JComboxespecialista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboxespecialistaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("ESPECIALISTA EN:");

        JButtonguardar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        JButtonguardar.setText("GUARDAR");
        JButtonguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JbuttonGuardarDatos(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addGap(972, 972, 972))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Jnombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Japellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Jusuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(66, 66, 66)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(Jpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(JComboxespecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(Jedadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(JRadioM)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(JRadioF)))
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(JDatenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(JButtonguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnombretxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Japellidotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JDatenacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Jedadtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(JRadioM)
                        .addComponent(JRadioF)
                        .addComponent(jLabel6)))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jusuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Jpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboxespecialista, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addComponent(JButtonguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbuttonGuardarDatos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JbuttonGuardarDatos
         RegistrarDatos();
    }//GEN-LAST:event_JbuttonGuardarDatos

    private void cargardatosCombox(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargardatosCombox
        // cargar los datos del combox
       
       if(especialidad!=null){
       JComboxespecialista.removeAllItems();
       especialidad.removeAll(especialidad);
       Combox1.removeAllElements();
       generarEspecialista().removeAllElements();
       }
                      
        JComboxespecialista.setModel(generarEspecialista());        
    }//GEN-LAST:event_cargardatosCombox

    private void JComboxespecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboxespecialistaActionPerformed
//         TODO add your handling code here:
//        try{            
//       JOptionPane.showMessageDialog(null,"Cantidad de espacio: "+JComboxespecialista.getItemAt(JComboxespecialista.getSelectedIndex()));     
//        }catch(Exception ex){
//       System.err.println(ex.getMessage());
//        }
       
    }//GEN-LAST:event_JComboxespecialistaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonguardar;
    private javax.swing.JComboBox<String> JComboxespecialista;
    private com.toedter.calendar.JDateChooser JDatenacimiento;
    private javax.swing.JRadioButton JRadioF;
    private javax.swing.JRadioButton JRadioM;
    private javax.swing.JTextField Japellidotxt;
    private javax.swing.JTextField Jedadtxt;
    private javax.swing.JTextField Jnombretxt;
    private javax.swing.JPasswordField Jpasswordtxt;
    private javax.swing.JTextField Jusuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.ButtonGroup sexo;
    // End of variables declaration//GEN-END:variables
}
